name: web_polymask
description: A polygon merging library with web/svg implementation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  grid_space:
    git: https://github.com/doodlezucc/dart_grid_space.git

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^4.0.4
  test: ^1.17.8
